### ISSUE TITLE
Inconsistent test failures

### ISSUE THREAD

**Issue by srt32** [gocardless/hutch#131]
When running the test suite locally, I am seeing inconsistent test failures. Sometimes the suite passes. Sometimes I get 19 failures with errors that look like

```
Failures:
...
19) Hutch::Broker#set_up_amqp_connection with valid details #channel
     Failure/Error: before { broker.set_up_amqp_connection }
     Hutch::ConnectionError:
       couldn't connect to rabbitmq at amqp://calvin@not-localhost:5672/. Check your configuration, network connectivity and RabbitMQ logs.
     # ./lib/hutch/broker.rb:297:in `rescue in with_bunny_connection_handler'
     # ./lib/hutch/broker.rb:294:in `with_bunny_connection_handler'
     # ./lib/hutch/broker.rb:90:in `open_connection!'
     # ./lib/hutch/broker.rb:46:in `set_up_amqp_connection'
     # ./spec/hutch/broker_spec.rb:58:in `block (4 levels) in <top (required)>'
```

And then sometimes I get a single failure that looks like:

```
Failures:

  1) Hutch::Config.get for valid attributes with no overridden value should eq "localhost"
     Failure/Error: it { is_expected.to eq('localhost') }

       expected: "localhost"
            got: "broker.yourhost.com"

       (compared using ==)
     # ./spec/hutch/config_spec.rb:12:in `block (5 levels) in <top (required)>'

Finished in 0.23222 seconds (files took 0.43452 seconds to load)
85 examples, 1 failure

Failed examples:

rspec ./spec/hutch/config_spec.rb:12 # Hutch::Config.get for valid attributes with no overridden value should eq "localhost"
```

And then sometimes it passes again.  Any advice on how to get a more consistent suite running?  Thanks!

**Comment by michaelklishin** [comment]
What OS and Ruby version?

**Comment by srt32** [comment]
OSX Yosemite and Ruby 2.1.3

**Comment by michaelklishin** [comment]
I can't reproduce this (with 2.1.5 on Yosemite).
