### ISSUE TITLE
Config to support #fetch

### ISSUE THREAD

**Issue by olleolleolle** [gocardless/hutch#160]
This new line in broker.rb:

```ruby
port               = @config.fetch(:mq_port, (tls ? 5671 : 5672))
```

In hutch-0.16.0/, Config does not have `#fetch` yet and throws a NoMethodError: 

```
undefined method `fetch' for Hutch::Config:Module (NoMethodError)
```

To reproduce, try: 

```
--- ruby/hutch ‹master› » ./bin/hutch
2015-07-19T10:58:53Z 97408 INFO -- hutch booted with pid 97408
/Users/olle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hutch-0.16.0/lib/hutch/config.rb:103:in `method_missing': undefined method `fetch' for Hutch::Config:Module (NoMethodError)
	from /Users/olle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hutch-0.16.0/lib/hutch/broker.rb:77:in `open_connection!'
	from /Users/olle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hutch-0.16.0/lib/hutch/broker.rb:52:in `set_up_amqp_connection'
	from /Users/olle/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hutch-0.16.0/lib/hutch/broker.rb:19:in `connect'
	from /opt/src/opensource/ruby/hutch/lib/hutch.rb:38:in `connect'
	from /opt/src/opensource/ruby/hutch/lib/hutch/cli.rb:84:in `start_work_loop'
	from /opt/src/opensource/ruby/hutch/lib/hutch/cli.rb:22:in `run'
	from ./bin/hutch:7:in `<main>'
```

**Comment by michaelklishin** [comment]
Try 186a264eb61486e2cd9702e389e626cf6dbd110d and `0.17.0`.

**Comment by olleolleolle** [comment]
Huzzah! Much better!

```
--- ruby/hutch ‹master› » hutch
2015-07-19T11:43:34Z 98188 INFO -- hutch booted with pid 98188
2015-07-19T11:43:34Z 98188 INFO -- connecting to rabbitmq (amqp://guest@localhost:5672/)
W, [2015-07-19T13:43:34.302162 #98188]  WARN -- #<Bunny::Session:70127647515820 guest@localhost:5672, vhost=/, hosts=[localhost]>: Could not establish TCP connection to localhost:5672:
2015-07-19T11:43:34Z 98188 ERROR -- amqp connection error: could not establish tcp connection to any of the configured hosts
2015-07-19T11:43:34Z 98188 FATAL -- couldn't connect to rabbitmq at amqp://guest@localhost:5672/. Check your configuration, network connectivity and RabbitMQ logs.
2015-07-19T11:43:34Z 98188 INFO -- hutch terminated due to an error
--- ruby/hutch ‹master› » echo $?                                                                                                                  1 ↵
1
```
